name: test_task_2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  animated_toggle_switch: ^0.8.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/emotions/

  fonts:
    - family: Nunito
      fonts:
        # - asset: fonts/Inter-Regular.otf
        #   weight: 400
        # - asset: fonts/Inter-Medium.otf
        #   weight: 500
        # - asset: fonts/Inter-MediumItalic.otf
        #   weight: 500
        #   style: italic
        - asset: fonts/Nunito-Medium.ttf
          weight: 500
        - asset: fonts/Nunito-Regular.ttf
          weight: 400
        - asset: fonts/Nunito-Bold.ttf
          weight: 700
        - asset: fonts/Nunito-ExtraBold.ttf
          weight: 800
        # - asset: fonts/Inter-Black.otf
        #   weight: 900
